# Generated by Django 4.2.26 on 2025-11-16 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('bucket_key', models.CharField(max_length=300)),
                ('sha256', models.CharField(blank=True, max_length=128, null=True)),
                ('validation_enabled', models.BooleanField(default=False)),
                ('validation_status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.company')),
                ('creator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.businessentity')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documentos.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='businessentity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.company'),
        ),
    ]
