# Generated by Django 4.2.26 on 2025-11-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bucket_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
